baseurl = "https://decidelab.github.io/website/"
title = "DECIDE Lab"
languageCode = "en-us"
publishDir = "docs"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Theme to use
theme = "simple-hugo-theme"

# Pagination
paginate = 3
paginatePath = "page"

# Google analytics
# googleAnalytics = ""

# Copyright
copyright = "© 2020 — Phùng Khánh Lâm."

# Language
DefaultContentLanguage = "vn"

[languages]
  [languages.en]
    weight = 2
    [languages.en.menu]
      # Header
      [[menu.main]]
        url = "about/"
        name = "About"
        weight = 1
      [[menu.main]]
        url = "research/"
        name = "Reseach"
        weight = 2
      [[menu.main]]
        url = "teaching/"
        name = "Teaching"
        weight = 3
      [[menu.main]]
        url = "material/"
        name = "Resources"
        weight = 4        

      # Footer
      [[menu.footer]]
        url = "mailto:lampk@ump.edu.vn"
        name = "Contact"
        weight = 3
        
  [languages.vn]
    weight = 1
    [languages.vn.menu]
      # Header
      [[menu.main]]
        url = "about/"
        name = "Giới thiệu"
        weight = 1
      [[menu.main]]
        url = "research/"
        name = "Nghiên cứu"
        weight = 2
      [[menu.main]]
        url = "teaching/"
        name = "Giảng dạy"
        weight = 3
      [[menu.main]]
        url = "material/"
        name = "Tài liệu"
        weight = 4

      # Footer
      [[menu.footer]]
        url = "mailto:lampk@ump.edu.vn"
        name = "Liên hệ"
        weight = 3

# Highlighting
pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "vs"

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Links format
[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  # Date format (default: Jan 2, 2006)
  # datefmt  = "Jan 2, 2006"
